### ISSUE TITLE
TPython broken!

### ISSUE THREAD

**Issue by sontaimnt** [Techlord210/TPython#1]
```
pop-os:~/.local/bin$ tpy
Traceback (most recent call last):
  File "/home/sontaimnt/.local/bin/tpy", line 5, in <module>
    from main import main
ModuleNotFoundError: No module named 'main'
```

Tpython is currently broken.. it might be a packaging issue

**Comment by sontaimnt** [comment]
@Techlord210  1.5 is still broken when installing with pip

```
@pop-os:~$ pip install TPython
Defaulting to user installation because normal site-packages is not writeable
Collecting TPython
  Downloading TPython-1.5.tar.gz (5.1 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from TPython) (0.4.4)
Requirement already satisfied: jsonc_parser in ./.local/lib/python3.10/site-packages (from TPython) (1.1.5)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from TPython) (2.25.1)
Building wheels for collected packages: TPython
  Building wheel for TPython (setup.py) ... done
  Created wheel for TPython: filename=TPython-1.5-py3-none-any.whl size=2772 sha256=219226591de67e870c0f9d243d1ebc11f62d86002ac4cf802554884ff77864d2
  Stored in directory: /home/sontaimnt/.cache/pip/wheels/43/45/4b/cf873a9b183aad1754c16025464704a7a36738429d4d50fa17
Successfully built TPython
Installing collected packages: TPython
Successfully installed TPython-1.5
pop-os:~$ tpy
Traceback (most recent call last):
  File "/home/sontaimnt/.local/bin/tpy", line 5, in <module>
    from tpy.tpy import main
ModuleNotFoundError: No module named 'tpy.tpy'
```

**Comment by Techlord210** [comment]
Thanks for reporting issue can try to run `python3 -m tpy`

**Comment by sontaimnt** [comment]
same error besides there is already a lib in pypi known as tpy and `python3 -m tpy` causes conflict with TPython... if tpy lib is installed...

**Comment by Techlord210** [comment]
> same error besides there is already a lib in pypi known as tpy and `python3 -m tpy` causes conflict with TPython... if tpy lib is installed...

there are no libs called tpy except a tumx cli tool which was last updated 3 years ago
